### PR TITLE
Add cspad cbf test set from dials_regression

### PR DESCRIPTION
**Pull request by phyy-nx**
Further reducing dependencies on dials_regression

### CODE REVIEW

**Comment by phyy-nx** [comment]
Bump :)

**Comment by Anthchirp** [comment]
Fine in general. Could you rename `README` to `README.MD`, and add a link and DOI badge for the paper reference?

**Comment by phyy-nx** [comment]
Added an attempt at the link, but I don't know how to get a DOI badge for this paper so it looks weird

**Review by Anthchirp — APPROVED** [review]
Thanks for the reference. I've fixed up the badge.

I've also renamed the directory from `cspad_cbf` to `thermolysin_cspad`, as that's more in line with the existing directories. If you're happy with that then we can squash merge

**Comment by phyy-nx** [comment]
Looks good, thanks.  Merging.

**Pull request merged**
